"""Course design agent: AI-assisted course planning (chapters → lessons).

Generates a course outline (chapter/lesson structure) from a topic, with
optional grounding in ClassLib teaching material. Lesson CELL content is
generated by the LearningAgent (per lesson, after the instructor reviews
the outline).
"""

from .base_agent import BaseAgent


class CourseDesignAgent(BaseAgent):
    """Designs a course structure: chapters with lessons (outline only)."""

    def process_request(self, request_data):
        """
        Expected request_data:
            {'topic': str, 'difficulty': str, 'chapter_count': int,
             'source_material': str}
        """
        return self.design_course_outline(
            topic=request_data.get('topic'),
            difficulty=request_data.get('difficulty', 'beginner'),
            chapter_count=request_data.get('chapter_count', 3),
            source_material=request_data.get('source_material', ''),
        )

    def design_course_outline(self, topic, difficulty='beginner',
                              chapter_count=3, source_material=''):
        """
        Generate a course outline.

        Returns:
            dict: {"chapters": [{"title", "description",
                                 "lessons": [{"title", "description"}]}]}
        """
        system_prompt = f"""
        You are an expert curriculum designer for a Python teaching platform.
        Design a course outline on '{topic}' for {difficulty} level students.

        Return JSON ONLY with this exact structure:
        {{
            "chapters": [
                {{
                    "title": "第1章 ...",
                    "description": "本章简介（一句话）",
                    "lessons": [
                        {{"title": "1.1 ...", "description": "本单元要点（一句话）"}},
                        {{"title": "1.2 ...", "description": "本单元要点（一句话）"}}
                    ]
                }}
            ]
        }}

        Rules:
        1. Exactly {chapter_count} chapters, 2-4 lessons per chapter.
        2. Lesson titles use X.Y numbering matching the chapter.
        3. Progressive difficulty: foundations first, applications last.
        4. Chapter/lesson titles and descriptions in Chinese.
        5. Do NOT include cell content — only the outline.
        """

        prompt = f"""
        Design a {difficulty} level course outline for the topic '{topic}'.

        Focus on concepts students actually need to write Python: concepts,
        syntax, common patterns, debugging and real-world applications.
        """

        if source_material:
            prompt += f"""

        The following teaching material is available in our ClassLib and
        SHOULD be reflected in the outline (cover these sections/points in
        the appropriate chapters and lessons):

        {source_material}
        """

        result = self.generate_json(prompt, system_prompt, role='planner')
        if isinstance(result, list):  # model dropped the {"chapters": ...} wrapper
            return {'chapters': result}
        return result

    def design_chapter_lessons(self, chapter_title, course_topic, difficulty='beginner',
                               lesson_count=3, source_material=''):
        """Generate the lesson list (titles + descriptions) for ONE chapter.

        Returns:
            dict: {"lessons": [{"title", "description"}]}
        """
        system_prompt = f"""
        You are an expert curriculum designer for a Python teaching platform.
        Plan the lessons of one chapter for a {difficulty} level course.

        Return JSON ONLY with this exact structure:
        {{
            "lessons": [
                {{"title": "X.Y 标题", "description": "本单元要点（一句话）"}}
            ]
        }}

        Rules:
        1. Exactly {lesson_count} lessons.
        2. Titles carry the chapter's numbering (e.g. 第2章 → 2.1, 2.2 ...).
        3. Progressive difficulty within the chapter.
        4. Chinese titles and descriptions.
        """

        prompt = f"""
        Course topic: {course_topic}
        Chapter title: {chapter_title}

        Plan {lesson_count} lessons for this chapter. Each lesson is one
        teaching unit (a Jupyter-style notebook) of roughly 45 minutes.
        """

        if source_material:
            prompt += f"""

        The following teaching material is available in our ClassLib and
        SHOULD be reflected in the lesson plan (cover these points):

        {source_material}
        """

        result = self.generate_json(prompt, system_prompt, role='planner')
        if isinstance(result, list):  # model dropped the {"lessons": ...} wrapper
            return {'lessons': result}
        return result
