# Generated by Django 5.0 on 2026-01-11 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("learning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("points", models.IntegerField(default=10)),
                ("time_limit_seconds", models.IntegerField(blank=True, null=True)),
                (
                    "starter_code",
                    models.TextField(
                        blank=True, help_text="Initial code template for students"
                    ),
                ),
                ("solution_code", models.TextField(help_text="Reference solution")),
                (
                    "test_cases",
                    models.JSONField(
                        default=list, help_text="Test cases in JSON format"
                    ),
                ),
                ("total_submissions", models.IntegerField(default=0)),
                ("successful_submissions", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exercises",
                        to="learning.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exercises_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "exercises",
                "ordering": ["difficulty", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Hint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "points_penalty",
                    models.IntegerField(
                        default=2, help_text="Points deducted for viewing this hint"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hints",
                        to="training.exercise",
                    ),
                ),
            ],
            options={
                "db_table": "hints",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="HintUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage",
                        to="training.hint",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hint_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "hint_usage",
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("error", "Error"),
                            ("timeout", "Timeout"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "test_results",
                    models.JSONField(
                        blank=True, help_text="Detailed test case results", null=True
                    ),
                ),
                ("output", models.TextField(blank=True)),
                ("error_message", models.TextField(blank=True)),
                ("execution_time_ms", models.IntegerField(blank=True, null=True)),
                ("tests_passed", models.IntegerField(default=0)),
                ("tests_total", models.IntegerField(default=0)),
                ("points_awarded", models.IntegerField(default=0)),
                ("hints_used", models.IntegerField(default=0)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="training.exercise",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "submissions",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(
                fields=["difficulty", "-created_at"],
                name="exercises_difficu_cfd140_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="exercise",
            index=models.Index(fields=["course"], name="exercises_course__bab357_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="hint",
            unique_together={("exercise", "order")},
        ),
        migrations.AlterUniqueTogether(
            name="hintusage",
            unique_together={("student", "hint")},
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["student", "exercise"], name="submissions_student_e88ca5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(fields=["status"], name="submissions_status_dcc854_idx"),
        ),
        migrations.AddIndex(
            model_name="submission",
            index=models.Index(
                fields=["-submitted_at"], name="submissions_submitt_113cfb_idx"
            ),
        ),
    ]
