# Generated by Django 5.2.8 on 2026-09-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_knowledgepoint"),
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="knowledge_points",
            field=models.ManyToManyField(
                blank=True, related_name="exercises", to="learning.knowledgepoint"
            ),
        ),
    ]
