# Generated by Django 5.2.8 on 2026-01-11 14:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_number",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="尝试次数",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "time_remaining_seconds",
                    models.IntegerField(
                        help_text="后端验证用，防止客户端作弊",
                        verbose_name="剩余时间(秒)",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="得分(%)",
                    ),
                ),
                (
                    "is_submitted",
                    models.BooleanField(default=False, verbose_name="已提交"),
                ),
                (
                    "randomization_seed",
                    models.IntegerField(
                        help_text="确保每次尝试题目顺序一致", verbose_name="随机种子"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生考试",
                "verbose_name_plural": "学生考试",
                "db_table": "student_exams",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("multiple_choice", "选择题"),
                            ("code", "编程题"),
                            ("essay", "简答题"),
                            ("true_false", "判断题"),
                        ],
                        max_length=20,
                        verbose_name="题目类型",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="题目内容")),
                (
                    "points",
                    models.IntegerField(
                        default=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="分值",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="题目顺序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "考试题目",
                "verbose_name_plural": "考试题目",
                "db_table": "exam_questions",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="考试标题")),
                ("description", models.TextField(verbose_name="考试描述")),
                (
                    "duration_minutes",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="考试时长(分钟)",
                    ),
                ),
                (
                    "passing_score",
                    models.IntegerField(
                        help_text="百分比形式, 例如: 60 表示60%",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="及格分数(%)",
                    ),
                ),
                (
                    "max_attempts",
                    models.IntegerField(
                        default=3,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="最大尝试次数",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="已发布"),
                ),
                (
                    "randomize_questions",
                    models.BooleanField(default=True, verbose_name="随机打乱题目顺序"),
                ),
                (
                    "show_results_immediately",
                    models.BooleanField(default=True, verbose_name="立即显示结果"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_exams",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "考试",
                "verbose_name_plural": "考试",
                "db_table": "exams",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "student_exam",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="certificate",
                        serialize=False,
                        to="examination.studentexam",
                        verbose_name="学生考试",
                    ),
                ),
                (
                    "certificate_pdf",
                    models.FileField(
                        upload_to="certificates/%Y/%m/", verbose_name="证书PDF"
                    ),
                ),
                (
                    "verification_code",
                    models.CharField(max_length=32, unique=True, verbose_name="验证码"),
                ),
                (
                    "issued_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="颁发时间"),
                ),
            ],
            options={
                "verbose_name": "证书",
                "verbose_name_plural": "证书",
                "db_table": "certificates",
            },
        ),
        migrations.CreateModel(
            name="CodeQuestion",
            fields=[
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="examination.question",
                        verbose_name="题目",
                    ),
                ),
                (
                    "starter_code",
                    models.TextField(
                        blank=True,
                        help_text="提供给学生的初始代码模板",
                        verbose_name="起始代码",
                    ),
                ),
                (
                    "test_cases",
                    models.JSONField(
                        help_text="格式: [{'input': '...', 'expected_output': '...', 'is_hidden': false}, ...]",
                        verbose_name="测试用例",
                    ),
                ),
                ("solution_code", models.TextField(verbose_name="参考答案")),
                ("explanation", models.TextField(blank=True, verbose_name="解题思路")),
            ],
            options={
                "verbose_name": "编程题",
                "verbose_name_plural": "编程题",
                "db_table": "exam_code_questions",
            },
        ),
        migrations.CreateModel(
            name="EssayQuestion",
            fields=[
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="examination.question",
                        verbose_name="题目",
                    ),
                ),
                (
                    "word_limit",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="字数限制",
                    ),
                ),
                (
                    "rubric",
                    models.TextField(
                        blank=True,
                        help_text="评分时的参考标准",
                        verbose_name="评分标准",
                    ),
                ),
                (
                    "sample_answer",
                    models.TextField(blank=True, verbose_name="参考答案"),
                ),
            ],
            options={
                "verbose_name": "简答题",
                "verbose_name_plural": "简答题",
                "db_table": "exam_essay_questions",
            },
        ),
        migrations.CreateModel(
            name="MultipleChoiceQuestion",
            fields=[
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="examination.question",
                        verbose_name="题目",
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        help_text="格式: {'A': '选项A内容', 'B': '选项B内容', 'C': '选项C内容', 'D': '选项D内容'}",
                        verbose_name="选项",
                    ),
                ),
                (
                    "correct_answer",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                        verbose_name="正确答案",
                    ),
                ),
                ("explanation", models.TextField(blank=True, verbose_name="答案解析")),
            ],
            options={
                "verbose_name": "选择题",
                "verbose_name_plural": "选择题",
                "db_table": "exam_mc_questions",
            },
        ),
        migrations.CreateModel(
            name="TrueFalseQuestion",
            fields=[
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="examination.question",
                        verbose_name="题目",
                    ),
                ),
                (
                    "correct_answer",
                    models.BooleanField(
                        verbose_name="正确答案 (True=正确, False=错误)"
                    ),
                ),
                ("explanation", models.TextField(blank=True, verbose_name="答案解析")),
            ],
            options={
                "verbose_name": "判断题",
                "verbose_name_plural": "判断题",
                "db_table": "exam_tf_questions",
            },
        ),
        migrations.AddField(
            model_name="studentexam",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_attempts",
                to="examination.exam",
                verbose_name="考试",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="examination.exam",
                verbose_name="所属考试",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentexam",
            unique_together={("student", "exam", "attempt_number")},
        ),
        migrations.CreateModel(
            name="ExamAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer_data",
                    models.JSONField(
                        help_text="格式根据题型: {'selected': 'A'} 或 {'code': '...', 'output': '...'} 或 {'text': '...'}",
                        verbose_name="答案数据",
                    ),
                ),
                (
                    "points_awarded",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="获得分数",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(blank=True, null=True, verbose_name="是否正确"),
                ),
                ("feedback", models.TextField(blank=True, verbose_name="评分反馈")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="答题时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_answers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="评分者",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="examination.question",
                        verbose_name="题目",
                    ),
                ),
                (
                    "student_exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="examination.studentexam",
                        verbose_name="学生考试",
                    ),
                ),
            ],
            options={
                "verbose_name": "考试答案",
                "verbose_name_plural": "考试答案",
                "db_table": "exam_answers",
                "unique_together": {("student_exam", "question")},
            },
        ),
    ]
