# Generated by Django 5.2.8 on 2026-01-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examanswer",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待评分"),
                    ("graded", "已评分"),
                    ("needs_review", "需人工复核"),
                ],
                default="pending",
                max_length=20,
                verbose_name="评分状态",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                choices=[("easy", "简单"), ("medium", "中等"), ("hard", "困难")],
                default="medium",
                max_length=10,
                verbose_name="难度",
            ),
        ),
    ]
