# Generated by Django 5.2.8 on 2026-09-17 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("examination", "0002_examanswer_status_question_difficulty"),
        ("learning", "0002_knowledgepoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exams",
                to="learning.course",
                verbose_name="关联课程",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="knowledge_points",
            field=models.ManyToManyField(
                blank=True,
                related_name="questions",
                to="learning.knowledgepoint",
                verbose_name="知识点",
            ),
        ),
    ]
