# Generated by Django 5.2.8 on 2026-09-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIGenerationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent",
                    models.CharField(
                        help_text="调用方（Agent 类名或 chat）", max_length=50
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("prompt", models.TextField()),
                ("response", models.TextField(blank=True)),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                ("duration_ms", models.IntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ai_generation_history",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["agent", "-created_at"],
                        name="ai_generati_agent_5cbf26_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="ai_generati_created_04f067_idx"
                    ),
                ],
            },
        ),
    ]
